apiVersion: v1
kind: Service
 
metadata:
  name: realtime
  namespace: realtime
 
spec:
  type: NodePort
 
  selector:
    app: realtime
 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
